esphome:
  name: garage-assistant

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "UppukkuChappani"
  password: "feededdeed"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Assistant"
    password: "ZboxMCqFS8ev"

captive_portal:
    